name: Build and Publish WPF App

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: windows-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/App.sln

    - name: Build solution
      run: dotnet build src/App.sln --configuration Release --no-restore

    - name: Publish app
      run: dotnet publish src/App.sln --configuration Release --output publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wpf-build
        path: publish/

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: "✅ Build terminé avec succès"
        to: gael.pidoux@ynov.com
        from: ci@geoloom.dev
        body: |
          Le pipeline CI/CD GeoLoom WPF s’est terminé avec succès. 🎉
