name: Build and Publish WPF App

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: windows-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore GeoLoom.sln

    - name: Build solution
      run: dotnet build MinimalApp/MinimalApp.csproj --configuration Release

    - name: Publish app
      run: dotnet publish MinimalApp/MinimalApp.csproj --configuration Release --output MinimalApp/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wpf-build
        path: MinimalApp/publish/
    - name: Debug mail (output vars)
      run: |
        echo "TO: ${{ secrets.SENDGRID_API_KEY != '' && 'OK' || '❌ MISSING' }}"


    - name: Send email via HTTP SendGrid API
      run: |
        curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data '{
            "personalizations": [{"to": [{"email": "gael.pidoux@ynov.com"}]}],
            "from": {"email": "gael.pidoux@ynov.com"},
            "subject": "✅ Build terminé avec succès",
            "content": [{"type": "text/plain", "value": "Le pipeline CI/CD s’est terminé avec succès."}]
          }'



