name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      backupPath:
        description: 'Faux chemin de backup à restaurer mais c est faux donc tqt mon reuf'
        required: true
        default: 'C:\Backups\MyApp_20250610_150000'

jobs:
  rollback:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run rollback script
      shell: pwsh
      run: |
        ./rollback/restore.ps1 -backupPath "${{ github.event.inputs.backupPath }}"
